// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_ovwWtoVsOMvNjsoN7NFzEdoqu7P3PA',
    appId: '1:80118378659:web:7b774344a34ca34c3c8f16',
    messagingSenderId: '80118378659',
    projectId: 'olympia-42ab2',
    authDomain: 'olympia-42ab2.firebaseapp.com',
    storageBucket: 'olympia-42ab2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbbyLGia_NMNimPNhX3HHrhkz_BRUFknw',
    appId: '1:80118378659:android:25579b45dc53ded63c8f16',
    messagingSenderId: '80118378659',
    projectId: 'olympia-42ab2',
    storageBucket: 'olympia-42ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5CPHnU0m2W07xxLZzkSLLajHvVarvR8',
    appId: '1:80118378659:ios:24cf3797398e68d23c8f16',
    messagingSenderId: '80118378659',
    projectId: 'olympia-42ab2',
    storageBucket: 'olympia-42ab2.appspot.com',
    iosBundleId: 'com.example.olympia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5CPHnU0m2W07xxLZzkSLLajHvVarvR8',
    appId: '1:80118378659:ios:24cf3797398e68d23c8f16',
    messagingSenderId: '80118378659',
    projectId: 'olympia-42ab2',
    storageBucket: 'olympia-42ab2.appspot.com',
    iosBundleId: 'com.example.olympia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD_ovwWtoVsOMvNjsoN7NFzEdoqu7P3PA',
    appId: '1:80118378659:web:05d34cb6aa6eda0d3c8f16',
    messagingSenderId: '80118378659',
    projectId: 'olympia-42ab2',
    authDomain: 'olympia-42ab2.firebaseapp.com',
    storageBucket: 'olympia-42ab2.appspot.com',
  );
}
